---

defaults: &defaults
  docker:
    - image: canonicalwebteam/dev
  working_directory: /srv

version: 2
jobs:
  lint-scss:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install yarn dependencies
          command: yarn install
      - run:
          name: Lint scss with sass-lint
          command: yarn run lint-scss
  lint-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: Lint webapp with Black
          command: yarn run lint-python
  test-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip3 install -r requirements.txt
      - run:
          name: Run tests with coverage
          command: |
            yarn run test-python
            bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build:
    jobs:
      - lint-scss
      - lint-python
      - test-python
